name: Release

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Import Secrets
        id: secrets
        uses: hashicorp/vault-action@v2.4.2
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: github
          githubToken: ${{ secrets.GH_TOKEN }}
          secrets: |
            kv/data/pmlo/services/github/pomelo-bot gh_token ;
            kv/data/pmlo/services/npm/pomelo-bot npm_token ;
        
      - name: Checkout
        uses: actions/checkout@v3

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        with:
          branch: master
          extra_plugins: |
            @semantic-release/git
            @semantic-release/changelog
        env:
          GH_TOKEN: ${{ steps.secrets.outputs.GH_TOKEN }}
          NPM_TOKEN: ${{ steps.secrets.outputs.NPM_TOKEN }}
